# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='主机IP')),
                ('other_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他IP')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口号')),
                ('username', models.CharField(blank=True, max_length=16, null=True, verbose_name='管理用户名')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码')),
                ('system_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统类型')),
                ('status', models.IntegerField(blank=True, choices=[(0, '在用'), (1, '闲置')], default=1, null=True, verbose_name='机器状态')),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目名')),
                ('person', models.CharField(max_length=30, verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='应用/服务名')),
                ('type', models.CharField(choices=[(0, '应用'), (1, '服务')], max_length=20, verbose_name='服务还是应用')),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendshow.Host', verbose_name='主机')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ManyToManyField(to='sendshow.Service', verbose_name='所拥有的服务'),
        ),
    ]
