# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendshow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hosts',
        ),
        migrations.AddField(
            model_name='service',
            name='hosts',
            field=models.ManyToManyField(to='sendshow.Host', verbose_name='主机'),
        ),
    ]
