# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendshow', '0003_auto_20170724_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.BooleanField(default=True, verbose_name='服务运行状态'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.IntegerField(choices=[(0, '应用'), (1, '服务')], verbose_name='服务还是应用'),
        ),
    ]
