# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendshow', '0004_auto_20170725_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='monitor',
            field=models.CharField(blank=True, max_length=128, verbose_name='监测地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(blank=True, default=22, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.IntegerField(default=0, verbose_name='服务运行状态'),
        ),
    ]
