# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendshow', '0006_auto_20170725_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.IntegerField(choices=[(0, '未知'), (1, '停止'), (2, '运行')], verbose_name='服务运行状态'),
        ),
    ]
